services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    env_file:
      - .env
    depends_on:
      - message-broker
      - cache
      - dlq-cache
      - tracing
    restart: unless-stopped

  message-broker:
    image: bitnami/kafka:latest
    ports:
      - "29092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    networks:
      - internal-network

  cache:
    image: redis:latest
    ports:
      - "6389"
    networks:
      - internal-network

  dlq-cache:
    image: redis:latest
    ports:
      - "6390"
    networks:
      - internal-network

  tracing:
    image: jaegertracing/all-in-one:latest
    ports:
      - "14268"
      - "16685"
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge